### PR TITLE
Revisit oscar19 support

### PR DESCRIPTION
**Pull request by phc007**
Initial settings for OSCAR 19 ON in place, tested and appears stable on a copy of Ontario production data.  This includes pdf generation from html

### CODE REVIEW

**Comment by phc007** [comment]
Thanks Fred
You are right of course, however I am new to github and don't know how to
do this from the website (unlike bitbucket where its a simple select squash
merge)
What do you suggest?
================
Peter Hutten-Czapski
Haileybury Ontario

"The attitude that ‘if rural people want these services they’ll have to
come to the city to get them’ is simply not acceptable…” (Newbery, 1999)

Before printing, think about the environment. Avant d' imprimer, pensez à
l'environnement.

**Comment by fredngo** [comment]
@phc007 Ah, you simply have to do all the operations in the command line, and then re-push when you're done.

Look up the `git rebase -i` command. I haven't read this article but it came up via a quick google and the title sounds promising:

https://medium.com/@slamflipstrom/a-beginners-guide-to-squashing-commits-with-git-rebase-8185cf6e62ec

**Comment by phc007** [comment]
yup
beginners guide is my type of resource!
I'll give it a spin
================
Peter Hutten-Czapski
Haileybury Ontario

"The attitude that ‘if rural people want these services they’ll have to
come to the city to get them’ is simply not acceptable…” (Newbery, 1999)

Before printing, think about the environment. Avant d' imprimer, pensez à
l'environnement.

**Comment by phc007** [comment]
Fred
I'm getting this error when I try to push a squashed commit

Enumerating objects: 19, done. Counting objects: 100% (19/19), done. Delta
compression using up to 4 threads Compressing objects: 100% (10/10), done.
Writing objects: 100% (11/11), 24.33 KiB | 8.11 MiB/s, done. Total 11
(delta 8), reused 3 (delta 1), pack-reused 0 remote: Resolving deltas: 100%
(8/8), completed with 8 local objects. remote: error: GH006: Protected
branch update failed for refs/heads/master. remote: error: At least 1
approving review is required by reviewers with write access. To
https://github.com/open-osp/open-osp.git ! [remote rejected] master ->
master (protected branch hook declined) error: failed to push some refs to '
https://github.com/open-osp/open-osp.git'
================
Peter Hutten-Czapski
Haileybury Ontario

"The attitude that ‘if rural people want these services they’ll have to
come to the city to get them’ is simply not acceptable…” (Newbery, 1999)

Before printing, think about the environment. Avant d' imprimer, pensez à
l'environnement.

**Comment by fredngo** [comment]
Not sure exactly.

Did you try to push to `master` instead of the branch?

I'm not an admin so I'm not sure what the security settings are.

But it's probably best to work off your own fork of the repo, and then request a pull request from a branch on your repo to this repo. That is quite a standard way of working in most projects.

**Comment by phc007** [comment]
I have taken your advice, squashed commit should be ready for you now
================
Peter Hutten-Czapski
Haileybury Ontario

"The attitude that ‘if rural people want these services they’ll have to
come to the city to get them’ is simply not acceptable…” (Newbery, 1999)

Before printing, think about the environment. Avant d' imprimer, pensez à
l'environnement.

**Pull request closed without merging**
