### PR TITLE
deploy-oscar-open-osp-favicon

### PR DESCRIPTION
**Pull request by warrendennis**
I spent a lot of time trying to get Open OSP deployed with no luck. Publishing changes does not seem to work.

Therefore this has not been tested properly.  Please make it work :)

### CODE REVIEW

**Comment by countable** [comment]
@warrendennis "I spent a lot of time trying to get Open OSP deployed with no luck. Publishing changes does not seem to work."

How does this relate to this PR? Can you create a new issue indicating the commands you tried, the result and the expected result?

**Comment by warrendennis** [comment]
This is related to the PR because the PR contains code to "deploy oscar open osp favicon".  This issue along with another were opened in March.  

See other ticket: https://github.com/open-osp/open-osp/issues/100 regarding deployment issues.

**Comment by countable** [comment]
Ok, so you've tested this locally, but can't publish the change?

**Comment by warrendennis** [comment]
I think that’s what happened.  I’ve tried every method.

**Pull request merged**
